AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

  Sample SAM Template for sam-test

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment (prod, qa, dev)"
    AllowedValues:
      - prod
      - qa
      - dev

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Mappings:
  EnvConfig:
    dev:
      EnvVar1: "dev-value1"
      EnvVar2: "dev-value2"
    qa:
      EnvVar1: "qa-value1"
      EnvVar2: "qa-value2"
    prod:
      EnvVar1: "prod-value1"
      EnvVar2: "prod-value2"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENV: !Ref Environment
          EnvVar1: !FindInMap [EnvConfig, !Ref Environment, EnvVar1]
          EnvVar2: !FindInMap [EnvConfig, !Ref Environment, EnvVar2]

  HelloWorldFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HelloWorldFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HelloWorldApi}/*/POST/hello"

  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "HelloWorldApi-${Environment}"
      StageName: !Ref Environment
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Sub "HelloWorldApi-${Environment}"
          version: "1.0"
        paths:
          /hello:
            post:
              x-amazon-apigateway-integration:
                type: "aws"
                httpMethod: "POST"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
                passthroughBehavior: "when_no_match"
                requestParameters:
                  'integration.request.header.X-Amz-Invocation-Type': "'Event'"
                responses:
                  default:
                    statusCode: "202"
              responses:
                '202':
                  description: Accepted

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub "ApplicationInsights-SAM-${AWS::StackName}-${Environment}"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for ${Environment} stage for Hello World function"
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']
  IsQa: !Equals [!Ref Environment, 'qa']
  IsDev: !Equals [!Ref Environment, 'dev']
